### ISSUE TITLE
Unable to create Word and XML Documents when reporting on vSphere

### ISSUE THREAD

**Issue by MrZumma** [tpcarman/As-Built-Report#16]
I have narrowed down the module that is throwing the error below in PS.  In vSphere\vSphere.json, when the InfoLevel for VMhost is set to 3 or higher, the below error is thrown in the PowerShell window.

I have also disabled all other InfoLevel options except for VMhost, and the error is still thrown.  It is not thrown for any other module.

I have tested all four output methods.  Only Word and XML output fail with the error below.  The HTML and TEXT options create the report as expected and does not throw the error below.

**Screenshot**
![image](https://user-images.githubusercontent.com/42972594/45043307-73a75680-b032-11e8-8d0e-5ec1778d665c.png)

**Desktop**
 - OS: Windows 10
 - PowerShell: 5.1
 - PowerCLI: 10.0
 - PScribo: 0.7.24
 - As-Built-Report: 0.2.0

**Comment by tpcarman** [comment]
Thanks @MrZumma for raising this issue. This is the same issue a work colleague of mine encountered only the other day. Good job on isolating the section, however does the report generate without errors if you disable the VMhost section and leave the others on InfoLevel 3? I suspect it could also be an issue with PScribo which I might ask @iainbrighton to take a look at.

**Comment by MrZumma** [comment]
You are welcome and glad I can help a little.

While leaving VMhost at InfoLevel 0, I have tested all the others (see exception below) with an InfoLevel of 1 through 5.  The error does not occur at any level as long as VMhost is at an InfoLevel of 2 or lower.

** I should have included this initially, but vSAN, NSX, and SRM are not used in our environment.  Those three  options have remained at an InfoLevel of 0 through all of my testing.

**Comment by DrBob5188** [comment]
For what it's worth the issue seems to be caused by the use of isolated storage.  There is some information in a comment by Tim Lewis on [this blog post](http://rekiwi.blogspot.com/2008/12/unable-to-determine-identity-of-domain.html).  There is a Powershell solution suggested [here](https://social.msdn.microsoft.com/Forums/silverlight/en-US/a4503126-303d-4f10-9226-164e36cff9e9/deploying-a-dacpac-via-powershell-caused-error-8220unable-to-determine-the-identity-of?forum=ssdt). I am guessing that running their suggested code before importing the PScribo module may make a difference, but to be honest I couldn't reproduce the fault in the limited testing I have done.  Hope that helps.

**Comment by DrBob5188** [comment]
I just looked again at New-AsBuiltReport.ps1 and since #requires statements are performed before script execution
`#requires -Modules @{ModuleName="PScribo";ModuleVersion="0.7.24"}`
will need to be replaced with
`import-module PScribo`

and the pre-amble code to set the security evidence inserted before the import-module command.

**Comment by ryan-jan** [comment]
Hi @DrBob5188, thanks for investigating this so thoroughly. I also came to the conclusion that it is caused by PScribo using `System.IO.IsolatedStorage`. Rather than hack a fix into our script I am hoping that we can get the PScribo source code fixed. I will open an issue on the PScribo repo.

**Comment by DrBob5188** [comment]
No problem. I did manage to reproduce the issue and test the preamble code does indeed fix the problem so there is at least that workaround for people having the issue.  Also fwiw, my understanding of the problem is that the issue isn't inherently with PScribo but rather the calling app domain. The only fix I could see possible in PScribo would be to track the size of the xml/stream writer and flush it periodically to avoid hitting whatever memory limit makes the .net framework use isolated storage. Seems pretty awful to me though. Hopefully someone with a better understanding of the app domain issue can chip in to explain the issue a little better.

**Comment by DrBob5188** [comment]
Ok, I just confirmed it is definitely a problem with the powershell environment.  You can reproduce it quite simply with these 2 lines of script
`$InitialEvidence = [System.Threading.Thread]::GetDomain().evidence
[System.IO.IsolatedStorage.IsolatedStorageFile]::GetUserStoreForDomain()`

Note that it fails in plain old PowerShell but works fine in the powershell_ise.  I think, although I haven't tested just yet, that the #requires statement will be fine as long as the environment is fixed up prior to making the calls to write the word document.

I couldn't figure out why there would be a different app domain for the caller and the loaded module, but upon reflection there shouldn't be and it's just the initial conditions instantiated by PowerShell.

**Comment by iainbrighton** [comment]
Sorry - a bit late to the party here as I've just come back off holiday. Is this related to the size of the Word ZIP file created, e.g. when it's over xMB in size?

**Comment by DrBob5188** [comment]
Yes it is Ian.  I think the magic number is about 8 mb. I can reliably reproduce the issue in PScribo by taking the authoring example and wrapping everything from the first page break through the end of the last section in a for loop.  300 iterations will get me the error, but your mileage may vary.
It's a tricky problem since the call to isolatedstorage is buried somewhere in the .NET framework.  Apart from the seemingly  dodgy workarounds of modifying the appdomain, flushing the xmlwriter periodically or running in the PowerShell ISE I can't see an obvious way around it, but I'll be keen to see where you land on it after examining the issue.

**Comment by tpcarman** [comment]
Issue moved to [new repository](https://github.com/AsBuiltReport/AsBuiltReport.Core/issues/17)
