### ISSUE TITLE
Issue with JSON config file conversion causes blank report output.

### ISSUE THREAD

**Issue by CRad14** [tpcarman/As-Built-Report#40]
Hey, I am very familiar and have used powershell/powercli for a long time, but I just downloaded this today and cannot get it to give me anything but an empty report. 

Tried different formats for output. Tried different vSphere environments, all I get is an empty report. 
This is how I am currently trying to run

New-Asbuiltreport -target vcenter -type vSphere -credentials (get-credential) -format html -healthchecks

I was able to import the psd1 file fine to get the cmdlet name.....and it clearly is creating the doc,html file, but it is just empty.

Any thoughts?

**Comment by ryan-jan** [comment]
Could you try the `master` branch to see if that gives you a different result. We recently converted the project to a module and I want to see if that is the issue. The `master` branch is still configured as a script so you would run `New-AsBuiltReport.ps1`.

Thanks for your feedback!

**Comment by CRad14** [comment]
Hmm, I got both the master and dev to work in one of the environments, was a credential problem :\

However they both are still not working in the second environment. 

One weird thing is when it asks for the Name of the report, version and status... the defaults for each are []   which is odd, potentially related to why the whole thing isn't working.

**Comment by ryan-jan** [comment]
OK that is good news. I will take a look at how the credentials are being handled. It sounds as though we need to validate that a valid connection to vCenter was actually made and throw an error if not. 

When the prompts run to specify the name, version etc. of the report, if you enter custom information instead of accepting the defaults does that work?

**Comment by ryan-jan** [comment]
Hi, 

Just to update you. @mattallford has found what we believe to be the root cause of this issue. It is to do with how we currently import the config `.json` files for the reports. @mattallford is working on the fix which will be pulled into both dev and master branches as soon as it is ready.

Thanks for raising this one!

**Comment by mattallford** [comment]
Hi,

Just to confirm, I did find the root cause of this issue and fixes have been pushed to both dev and master branches 14 days ago.

@tpcarman / @ryan-jan I believe this issue can now be closed.
