### ISSUE TITLE
Option to store the report data for offline re-processing

### ISSUE THREAD

**Issue by mc1903** [tpcarman/As-Built-Report#60]
**Describe the solution you'd like**
I would like the ability to collect report data from the live target (say vCenter) just the once and store it in a structured format (XML/JSON), which could then be played back into PScribo at a later date to create the actual As Built Report document. This would allow for offline re-processing of the report after I have left site. I would like to be able to change the report style. 

**Describe alternatives you've considered**
Not using the wrong style when creating the report!

**Comment by mattallford** [comment]
My initial thought is that this is probably more a request for the PScribo project rather than the AsBuiltReport project. As you say the data would need to be exported in a standard format which PScribo could then import as a standalone data feed file at a later date.

I think this would be best to open against the PScribo project GitHub, but will let @tpcarman weigh in as well.

**Comment by tpcarman** [comment]
Exporting and importing the data would be possible using `Export-CliXml` & `Import-CliXml`, however the document formatting / style is embedded in the output so I'm assuming a separate script/function would need to be written to clear and re-apply formatting.
